# Configuration for welcome - https://github.com/behaviorbot/welcome

# Configuration for new-issue-welcome - https://github.com/behaviorbot/new-issue-welcome
# Comment to be posted to on first time issues
newIssueWelcomeComment: >
  Hi ğŸ‘‹ Thanks for reaching out and opening your first issue here! We'll try to come back to you as soon as possible. â¤ï¸
  ![kenobi](https://media.giphy.com/media/Nx0rz3jtxtEre/giphy.gif)
# Configuration for new-pr-welcome - https://github.com/behaviorbot/new-pr-welcome
# Comment to be posted to on PRs from first time contributors in your repository
newPRWelcomeComment: >
  Thanks for opening this pull request! We'll make sure it's perfect before merging ğŸ¤—
  ![force](https://media.giphy.com/media/l1AsJoOWnvy0CuyFq/giphy.gif)
  
  Make sure to read the [contributing guide](https://github.com/neuropsychology/NeuroKit/blob/master/.github/CONTRIBUTING.rst#structure-and-code). Also, if you think that your contribution is worthy of it, you can consider adding yourself to the [Contributors list](https://github.com/neuropsychology/NeuroKit/blob/master/AUTHORS.rst) (feel free to ask us if you have any doubts).
  
# Configuration for first-pr-merge - https://github.com/behaviorbot/first-pr-merge
# Comment to be posted to on pull requests merged by a first time user
firstPRMergeComment: >
  ![landing](https://media.giphy.com/media/Dmydf2Zf2kOys/giphy.gif)

  Congrats on merging your first pull request! ğŸ‰ğŸ¾ We're looking forward to your next one!
# It is recommended to include as many gifs and emojis as possible! 