# Config file for automatic testing at travis-ci.org

language: python
dist: xenial
python:
  #- "nightly"
  #- "3.8-dev"
  #- "3.8"
  - "3.7"
  - "3.6"
  #- "3.5"


  
os:
  # - windows
  - linux
  # - osx
  
  
before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest
  - pip install codecov
  
install: 
  - pip install -U tox-travis
  - pip install numpy==1.18
  - pip install coverage
  - pip install flake8
  - pip install ".[test]"
    # Testing
  - pip install bioread
  - pip install mne
  - pip install pyentrp
  - pip install nolds
  - pip install biosppy
  - pip install cvxopt
  - pip install PyWavelets
  - pip install EMD-signal

script:
    - python setup.py install
    - tox
    - pytest --doctest-glob='*.py' neurokit2/bio -v
    - pytest --doctest-glob='*.py' neurokit2/complexity -v
    - pytest --doctest-glob='*.py' neurokit2/data -v
    - pytest --doctest-glob='*.py' neurokit2/ecg -v
    - pytest --doctest-glob='*.py' neurokit2/eda -v
    - pytest --doctest-glob='*.py' neurokit2/eeg -v
    - pytest --doctest-glob='*.py' neurokit2/emg -v
    - pytest --doctest-glob='*.py' neurokit2/epochs -v
    - pytest --doctest-glob='*.py' neurokit2/events -v
    - pytest --doctest-glob='*.py' neurokit2/hrv -v
    - pytest --doctest-glob='*.py' neurokit2/misc -v
    - pytest --doctest-glob='*.py' neurokit2/ppg -v
    - pytest --doctest-glob='*.py' neurokit2/rsp -v
    - pytest --doctest-glob='*.py' neurokit2/signal -v
    - pytest --doctest-glob='*.py' neurokit2/stats -v


after_success:
    - codecov
  
  
# Assuming you have installed the travis-ci CLI tool, after you
# create the Github repo and add it to Travis, run the
# following command to finish PyPI deployment setup:
# $ travis encrypt --add deploy.password
# deploy:
#   provider: pypi
#   distributions: sdist bdist_wheel
#   user: DominiqueMakowski
#   password:
#     secure: PLEASE_REPLACE_ME
#   on:
#     tags: true
#     repo: neuropsychology/NeuroKit
#     python: 3.7
