# Config file for automatic testing at travis-ci.org

language: python
python:
  - 3.6
  - 3.5
  - 3.4
  - 2.7

os:
  - linux
  #- osx
  
  
# Command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: pip install -U tox-travis


script:
    - python setup.py install
    - tox
#    - coverage run tests/test_neurokit2.py
#    - tox -e codecov
#   

    
# Command to run tests, e.g. python setup.py test
#script: tox
after_success:
  - codecov
  
  
# Assuming you have installed the travis-ci CLI tool, after you
# create the Github repo and add it to Travis, run the
# following command to finish PyPI deployment setup:
# $ travis encrypt --add deploy.password
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: DominiqueMakowski
  password:
    secure: PLEASE_REPLACE_ME
  on:
    tags: true
    repo: neuropsychology/NeuroKit
    python: 3.6
