name: ðŸŒ¼ Release checks

# on: [push, pull_request]
on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'
 
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install https://github.com/DominiqueMakowski/popularipy/zipball/master
        cd $GITHUB_WORKSPACE
        python setup.py install 
   
    - name: Run README_examples.py
      run: |
        cd $GITHUB_WORKSPACE/docs/readme
        python README_examples.py
        
    - name: Build package and test with twine
      run: |
        python -m pip install --upgrade setuptools pip wheel twine
        python setup.py sdist bdist_wheel
        python -m twine check dist/*