name: "ğŸ“œ Documentation builder"
on:
- pull_request

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: 0 # To be able to push refs to destination repo
    - name: Prepare Python ğŸ
      uses: actions/setup-python@v3

    - name: sphinx-action
      uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: "docs_wip/"
        pre-build-command: |
          pip install sphinx-book-theme
          pip install sphinxemoji
          pip install sphinx-copybutton
          pip install ipython
          pip install myst-parser
          pip install myst-nb
          pip install numpy
          pip install pandas
          pip install scipy
          pip install scikit-learn
          pip install matplotlib
          pip install mne
          pip install PyWavelets
          pip install astropy
          pip install seaborn
          pip install https://github.com/neuropsychology/neurokit/zipball/dev
        build-command:
          make html

    - name: Deploy ğŸš€
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs_wip/_build