name: Update README figures

on:
  push:
    branches:
      - dev


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'
 
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install https://github.com/DominiqueMakowski/popularipy/zipball/master
        cd $GITHUB_WORKSPACE
        python setup.py install 
   
    - name: Run README_examples.py
      run: |
        cd $GITHUB_WORKSPACE/docs/readme
        python README_examples.py
        # git add features.png
        # git add README_complexity_optimize.png
        # git add README_ecg.png
        # git add README_eda.png
        # git add README_embedding.png
        # git add README_emg.png
        # git add README_hdi.png
        # git add README_popularity.png
        # git add README_rsp.png
        # git add README_signalprocessing.png
        # git add README_simulation.png
        # git add workflow.png
        
    - name: Commit figures
      uses: EndBug/add-and-commit@v4
      with:
        message: "Commit README figures"
        ref: 'dev'
        add: "*.png"
        
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        